"""add year director chat_type user_rating

Revision ID: c4eba1bb8cc2
Revises: 0003
Create Date: 2026-04-07 21:06:50.683023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4eba1bb8cc2'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('year', sa.String(), nullable=True))
    op.add_column('media_items', sa.Column('director', sa.String(), nullable=True))
    op.alter_column('media_items', 'source',
               existing_type=postgresql.ENUM('kinopoisk', 'manual', name='mediasource'),
               type_=sa.Enum('KINOPOISK', 'MANUAL', name='mediasource', native_enum=False),
               nullable=True)
    op.alter_column('media_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_media_items_id'), table_name='media_items')
    op.add_column('queue_items', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.alter_column('queue_items', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'rejected', name='queueitemstatus'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='queueitemstatus', native_enum=False),
               nullable=True)
    op.alter_column('queue_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_queue_items_id'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_queue_id'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_status'), table_name='queue_items')
    op.drop_constraint(op.f('queue_items_media_id_fkey'), 'queue_items', type_='foreignkey')
    op.drop_constraint(op.f('queue_items_queue_id_fkey'), 'queue_items', type_='foreignkey')
    op.create_foreign_key(None, 'queue_items', 'queues', ['queue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'queue_items', 'media_items', ['media_id'], ['id'], ondelete='CASCADE')
    op.alter_column('queues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.alter_column('votes', 'vote_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('FOR', 'AGAINST', name='votetype', native_enum=False),
               existing_nullable=False)
    op.alter_column('votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_queue_item_user'), table_name='votes')
    op.drop_constraint(op.f('votes_queue_item_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'queue_items', ['queue_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('watched_history', 'queue_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watched_history', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_watched_history_chat_id'), table_name='watched_history')
    op.drop_index(op.f('ix_watched_history_id'), table_name='watched_history')
    op.drop_constraint(op.f('watched_history_queue_item_id_fkey'), 'watched_history', type_='foreignkey')
    op.drop_constraint(op.f('watched_history_media_id_fkey'), 'watched_history', type_='foreignkey')
    op.create_foreign_key(None, 'watched_history', 'media_items', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watched_history', 'queue_items', ['queue_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watched_history', type_='foreignkey')
    op.drop_constraint(None, 'watched_history', type_='foreignkey')
    op.create_foreign_key(op.f('watched_history_media_id_fkey'), 'watched_history', 'media_items', ['media_id'], ['id'])
    op.create_foreign_key(op.f('watched_history_queue_item_id_fkey'), 'watched_history', 'queue_items', ['queue_item_id'], ['id'])
    op.create_index(op.f('ix_watched_history_id'), 'watched_history', ['id'], unique=False)
    op.create_index(op.f('ix_watched_history_chat_id'), 'watched_history', ['chat_id'], unique=False)
    op.alter_column('watched_history', 'accepted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('watched_history', 'queue_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_queue_item_id_fkey'), 'votes', 'queue_items', ['queue_item_id'], ['id'])
    op.create_index(op.f('ix_votes_queue_item_user'), 'votes', ['queue_item_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.alter_column('votes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('votes', 'vote_type',
               existing_type=sa.Enum('FOR', 'AGAINST', name='votetype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    op.alter_column('queues', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'queue_items', type_='foreignkey')
    op.drop_constraint(None, 'queue_items', type_='foreignkey')
    op.create_foreign_key(op.f('queue_items_queue_id_fkey'), 'queue_items', 'queues', ['queue_id'], ['id'])
    op.create_foreign_key(op.f('queue_items_media_id_fkey'), 'queue_items', 'media_items', ['media_id'], ['id'])
    op.create_index(op.f('ix_queue_items_status'), 'queue_items', ['status'], unique=False)
    op.create_index(op.f('ix_queue_items_queue_id'), 'queue_items', ['queue_id'], unique=False)
    op.create_index(op.f('ix_queue_items_id'), 'queue_items', ['id'], unique=False)
    op.alter_column('queue_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('queue_items', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='queueitemstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'accepted', 'rejected', name='queueitemstatus'),
               nullable=False)
    op.drop_column('queue_items', 'message_id')
    op.create_index(op.f('ix_media_items_id'), 'media_items', ['id'], unique=False)
    op.alter_column('media_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_items', 'source',
               existing_type=sa.Enum('KINOPOISK', 'MANUAL', name='mediasource', native_enum=False),
               type_=postgresql.ENUM('kinopoisk', 'manual', name='mediasource'),
               nullable=False)
    op.drop_column('media_items', 'director')
    op.drop_column('media_items', 'year')
    # ### end Alembic commands ###